# Generated by Django 3.2.7 on 2021-09-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_howitworks_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedFieldsets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_field', models.CharField(max_length=255)),
                ('second_field', models.CharField(max_length=255)),
                ('third_field', models.CharField(max_length=255)),
            ],
        ),
    ]
