# Generated by Django 4.1.7 on 2023-02-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_namedfieldsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(related_name='chosen', to='sample.product')),
            ],
        ),
    ]
